export const SET_NUMBER = 'SET_NUMBER';
export const ADD_NUMBERS = 'ADD_NUMBERS';
export const SUBTRACT_NUMBERS = 'SUBTRACT_NUMBERS';
export const MULTIPLY_NUMBERS = 'MULTIPLY_NUMBERS';
export const DIVIDE_NUMBERS = 'DIVIDE_NUMBERS';
